### ISSUE TITLE
Smart Global

### ISSUE THREAD

**Issue by jamiew** [dewi-alliance/hotspot-manufacturers#16]
Name: Smart Global
 Author: @shpilkin
 Created: 2021-04-27
 Original PR: https://github.com/helium/HIP/pull/164
 Status: reviewing
 
 Rendered view: https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/smartglobal.md

**Comment by ChristinaR04** [comment]
Closed, this HIP19 application is inactive.
