### ISSUE TITLE
NEBRA Rock Chip Approval Conditions

### ISSUE THREAD

**Issue by Prooferz** [dewi-alliance/hotspot-manufacturers#166]
> I literally made a Github account just to give my own input here. I am batch 4, along with everyone else have been given massive unending delays, poor communication, misinformation, and lies. Nebra is barely capable (if at all) of completing current pre-orders but now wants to take on another manufacturing stream? I have given Nebra and @shawaj the benefit of the doubt for months! That ends here.
> 
> Dewi, **DO NOT** grant anything further to Nebra until they have demonstrated actual capabilities of delivering on promises. i.e delivering the THOUSANDS of delayed miners. Nebra has already single-handedly poisoned the trust in Helium Network for me and many others. Granting them another opening to do this again before they have handled their previous issues would be a huge mistake.

If DEWI/Helium is somehow still going to consider approving this application then 2 requirements MUST BE MET: (suggested by Youtube channel Crypto Compound)

1. Nebra is not allowed to accept preorders. All sales must be for units they have manufactured, in stock ready to ship.
2. Before Nebra can sell these new Rockchip miners to customers, they MUST offer existing customers of the original Nebra miner the option to replace their (extremely) delayed miner with this new ready-to-ship one.

These are the only reasonable contingencies if Nebra were actually going to get this approved.

Does this sound fair to you @shawaj ?

_Originally posted by @Rifle876 in https://github.com/dewi-alliance/hotspot-manufacturers/pull/119#issuecomment-955022534_

**Comment by Waiting4nebra** [comment]
The scam is obvious. 

he wants to cancel all our orders as he has seen other companies selling at a higher price point.

I for one want my hotspots.

im not in the business of giving out interest free loans for 7 months.

**Comment by ChristinaR04** [comment]
Hi @Prooferz ,

Thanks for your submission, but this repository is for Helium Improvement Proposals (HIPs) and is not an open discussion forum. I hear your frustrations but this is not the correct place for this.

If you'd like to write and submit a proposal, you should follow the format and process prescribed in HIP7, [Process for managing Helium Improvement Proposals](https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md)
Jamie has also written a guide to doing this using the github.com web interface: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/

I'm closing this as `invalid` but feel free to continue this discussion in Discord.

**Comment by Waiting4nebra** [comment]
> Hi @Prooferz ,
> 
> Thanks for your submission, but this repository is for Helium Improvement Proposals (HIPs) and is not an open discussion forum. I hear your frustrations but this is not the correct place for this.
> 
> If you'd like to write and submit a proposal, you should follow the format and process prescribed in HIP7, [Process for managing Helium Improvement Proposals](https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md) Jamie has also written a guide to doing this using the github.com web interface: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/
> 
> I'm closing this as `invalid` but feel free to continue this discussion in Discord.

Why not move it to the correct place rather than censor people?

**Comment by ChristinaR04** [comment]
> 
> 
> Why not move it to the correct place rather than censor people?
>
We're not censoring anyone, this repository is for Helium Improvement Proposals (HIPs) and is not an open discussion forum. 

There's already a discussion taking place in the [comment section here](https://github.com/dewi-alliance/hotspot-manufacturers/pull/119#issuecomment-951724108), as well as on discord. This topic was also discussed in the MOC Town Hall yesterday which was recorded for anyone who could not attend: (https://discord.com/channels/404106811252408320/813452716286017557/908060811531022386)

**Comment by shawaj** [comment]
> The scam is obvious.
> 
> he wants to cancel all our orders as he has seen other companies selling at a higher price point.
> 
> I for one want my hotspots.
> 
> im not in the business of giving out interest free loans for 7 months.

@Waiting4nebra We haven't tried to cancel anyone's orders. We don't cancel orders of anyone, unless they have specifically requested it.

Despite the RockPi version going to cost more, anyone with an existing order we will be maintaining the same price no questions asked if they ordered directly from Nebra.

We can't speak for other resellers/distributors of our products because they are separate businesses and we do not control what they do.
