### ISSUE TITLE
RevoFi

### ISSUE THREAD

**Issue by jamiew** [dewi-alliance/hotspot-manufacturers#19]
Name: RevoFi
 Author: @revofi-tkaplan
 Created: 2021-05-01
 Original PR: https://github.com/helium/HIP/pull/172
 Status: reviewing
 
 Rendered view: https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/revofi.md

**Comment by ChristinaR04** [comment]
Closed, this HIP19 application is inactive.
