### ISSUE TITLE
Linxdot Rockchip Hotspot

### ISSUE THREAD

**Issue by eriks12** [dewi-alliance/hotspot-manufacturers#192]
# Linxdot

 <img src="https://www.linxdot.com/images/logo-linxdot.png" alt="Linxdot logo" width=250 />

Application for updated versions of the Linxdot hotspot, LD1001, LD1002 as per HIP19

## Summary
This is an application for the approval of a second version of the Linxdot full hotspot, the overall design is the same as the first hotspot, with the difference being the main board is a RockChip design and not using CM4. The motivation for this change is to ensure that going into 2022, we are able to continue to manufacture units in large volumes and not be reliant on RPi CM4s that are in short supply in the foreseeable future. 

Linxdot is a device manufacturer for IoT. We are part of the same business structure as Fx Technology, a UK based smartphone & accessory manufacturer. Our smartphones have been shipped to over 60 countries globally and we have an active community of keyboard smartphone users. 

To date the Linxdot hotspots on the network are devices that we have shipped to our customers in US, EU and AUS. We have a development team working alongside a full support team for our Discord Channel and online customer enquiries. We are an open and responsive manufacturer, we aim to respond to all (sensible) enquiries within 24-28 hours.

## Product Information 
The Linxdot Helium Miner is a product of Fx Technology’s smartphone manufacturing expertise. The new versions have the same case design as our existing hotspot with the main difference that the main board is now a RockChip design. There are two versions of this design LD1001 (built in LORA chipset) and LD1002 (Lora module via PCIE slot), both have been sent to Dewi for audit.

<img src="https://www.linxdot.com/wp-content/uploads/2021/11/linxdot-rk-scaled.jpg" alt="Linxdot Rockchip" width=500 />

## Linxdot Helium Miner LD1001 and LD1002 Specifications:
 *   Rockchip CPU RK3566
 *   2GB RAM
 *   32GB Storage
 *   Concentrator based on SX1302
 *   Supported Bands: RU864, IN865, EU868, US915, AU915, KR920, AS923
 *   Bluetooth 5.0, BLE
 *   802.11 b/g/n/ac WiFi
 *   1Gbps Ethernet
 *   Power over Ethernet Support

Price point of Linxdot is £400 (ex VAT)

The device is updated automatically over the air, and it is simple to deploy and manage using the Helium Android & iOS app.

## Timelines

We are working towards the following timeline:
* Submit HIP 19 application - Nov 2021
* Dewi Hardware verification - Dec 2021
* Hardware certifications FCC/CE/UK - Nov 2021
* Manufacturing - Jan 2022
* Shipping to customers - late Jan/ early Feb 2022

## Customer Support

Our in-house customer service and support team provides international pre-sales support and after-sales support predominantly via email & Discord for Helium hotspots. This includes ongoing customer questions, queries, handling repair requests, and the replacement of hotspots for manufacturing defects or faulty units. We will aim to respond to all emails within 24-48 hours. 
We will also be accessible via Discord, Twitter, Facebook Messenger, and Instagram.

## Hardware Security

The Linxdot Miner is built through our comprehensive experience in creating mobile devices compliant with banking applications, storing sensitive user data, and providing enterprise support. Our Helium hotspot adopts the same security standards applied to hardware, software, and user systems.

ATECC608 has been integrated for storing the swarm-key used by the miner as per the requirements.

## Manufacturing Information

We have designed, manufactured our own consumer products (Helium hotspots, smartphones and accessories), and we are familiar with the challenges. The engineering team has expertise in electronics design, hardware and manufacturing on a large scale and of consumer / retail quality.  Our manufacturing partner (Eternity HK) is based in Shenzhen and also plays an advisory role to our business. We have a close working relationship with them which helps to get our manufacturing prioritised and delivery on time. For example, we’ve done FCC/CE approvals on our products, we have rigorous testing procedures and quality control measures to ensure that devices which roll off the production line are all to the highest standard. Our return rate on products due to manufacturing issues is so far less than less than 0.5%.

## Manufacturing Information

Previously approved by Dewi team

## Budget & Capital

As an existing global technology hardware business, we are in the financial position that we have sufficient reserves and cash flow to continue to manufacture continuous batches of devices into 2022. 

We have placed orders for some of the critical components (ECC and Lora parts) with long lead times needed for our estimated capacity (250k+) for the coming 12 months. 

## Other information

* Twitter profile - https://twitter.com/linxdot 
* Facebook profile - https://www.facebook.com/Linxdot 
* Other social profiles - Reddit (u/Linxdot), Telegram (https://t.me/Linxdot), Discord (https://discord.gg/8uDT3Hve),  Medium (Linxdot)    
* Website - https://www.linxdot.com 
* Payment methods are available - Credit cards, crypto payments and bank transfers
* Regions covered/shipped to - Worldwide Shipping

**Comment by ChristinaR04** [comment]
Duplicate issue, https://github.com/dewi-alliance/hotspot-manufacturers/issues/214
