### ISSUE TITLE
Layer 3

### ISSUE THREAD

**Issue by jamiew** [dewi-alliance/hotspot-manufacturers#20]
Name: Layer 3
 Author: @Layer3blockchain
 Created: 2021-05-07
 Original PR: https://github.com/helium/HIP/pull/173
 Status: reviewing
 
 Rendered view: https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/layer-3.md

**Comment by ChristinaR04** [comment]
Closed, this HIP19 application is inactive.
