### ISSUE TITLE
Heltec Hotspot MT-M2808

### ISSUE THREAD

**Issue by sajmi** [dewi-alliance/hotspot-manufacturers#211]
Would it be possible in the next firmware version to run the fan at a speed adapted to the processor temperature?
at the moment it always starts at the highest speed, which is quite noisy.
Thank you

**Comment by ChristinaR04** [comment]
Thanks for your submission, but this repository is for HIP-19 proposals.
If you'd like to write and submit a proposal, you should follow the format and process prescribed in HIP7, [Process for managing Helium Improvement Proposals](https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md)

Closing this as `invalid` but feel free to ask further questions on Discord.
