### ISSUE TITLE
i2SOM

### ISSUE THREAD

**Issue by jamiew** [dewi-alliance/hotspot-manufacturers#22]
Name: i2SOM
 Author: @Blackrose
 Created: 2021-05-08
 Original PR: https://github.com/helium/HIP/pull/175
 Status: reviewing
 
 Rendered view: https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/i2som.md

**Comment by ChristinaR04** [comment]
Closed, this HIP19 application is inactive.
