### ISSUE TITLE
lakshmiio

### ISSUE THREAD

**Issue by jamiew** [dewi-alliance/hotspot-manufacturers#24]
Name: lakshmiio
 Author: @mdgopal
 Created: 2021-06-18
 Original PR: https://github.com/helium/HIP/pull/212
 Status: reviewing
 
 Rendered view: https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/lakshmiio.md

**Comment by Sophi** [comment]
first draft for Lakshmi IO, there's another one here: https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/lakshmi-io.md
