### ISSUE TITLE
PiMios

### ISSUE THREAD

**Issue by jamiew** [dewi-alliance/hotspot-manufacturers#25]
Name: PiMios
 Author: @PiMios
 Created: 2021-06-19
 Original PR: https://github.com/helium/HIP/pull/214
 Status: reviewing
 
 Rendered view: https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/pimios.md

**Comment by ChristinaR04** [comment]
Closed, this HIP19 application is inactive.
