### ISSUE TITLE
BorIoT

### ISSUE THREAD

**Issue by jamiew** [dewi-alliance/hotspot-manufacturers#29]
Name: BorIoT
 Author: @hereismeaw
 Created: 2021-07-06
 Original PR: https://github.com/helium/HIP/pull/229
 Status: reviewing
 
 Rendered view: https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/boriot.md

**Comment by ChristinaR04** [comment]
Closed, this HIP19 application is inactive.
