### ISSUE TITLE
Lakshmi IO

### ISSUE THREAD

**Issue by jamiew** [dewi-alliance/hotspot-manufacturers#31]
Name: Lakshmi IO
 Author: @mdgopal
 Created: 2021-07-13
 Original PR: https://github.com/helium/HIP/pull/231
 Status: reviewing
 
 Rendered view: https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/lakshmi-io.md

**Comment by ChristinaR04** [comment]
Closed, this HIP19 application is inactive.
