### ISSUE TITLE
Innodev

### ISSUE THREAD

**Issue by jamiew** [dewi-alliance/hotspot-manufacturers#32]
Name: Innodev
 Author: @egtogamat
 Created: 2021-07-13
 Original PR: https://github.com/helium/HIP/pull/232
 Status: reviewing
 
 Rendered view: https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/innodev.md

**Comment by ChristinaR04** [comment]
Team has updated to a Light Hotspot design
