### ISSUE TITLE
Panther_X2 has wrong LoRa chipset

### ISSUE THREAD

**Issue by alhas** [dewi-alliance/hotspot-manufacturers#334]
Panther_X2 reported chipset as SX1302&SX1250, however they put SX1308&SX1257 in to thousands of devices and sent to customers. 
The reported .md file below.
https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/Panther%20X2.md

Their solution is just altering rssi information.
https://github.com/Panther-X/packet_forwarder/commit/65e3974f0a18fcd9ae78e53dedd0b2d56379874f

You can find discussions in their Discord channel.
As customers we were waiting latest technology in our device, they fooled us.

**Comment by lausser** [comment]
Closed means..."your problem, try to get your money back from the cheating chinese company, but don't bother us"?
