### ISSUE TITLE
iBudgetPCs

### ISSUE THREAD

**Issue by jamiew** [dewi-alliance/hotspot-manufacturers#35]
Name: iBudgetPCs
 Author: @mmaalouf97
 Created: 2021-07-14
 Original PR: https://github.com/helium/HIP/pull/235
 Status: reviewing
 
 Rendered view: https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/ibudgetpcs.md

**Comment by ChristinaR04** [comment]
Closed, this HIP19 application is inactive.
