### ISSUE TITLE
Jiangsu Rejeee Intelligent Technology

### ISSUE THREAD

**Issue by jamiew** [dewi-alliance/hotspot-manufacturers#40]
Name: Jiangsu Rejeee Intelligent Technology
 Author: @xiaowentao99
 Created: 2021-07-27
 Original PR: https://github.com/helium/HIP/pull/243
 Status: reviewing
 
 Rendered view: https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/rejeee.md

**Comment by ChristinaR04** [comment]
Closed, this HIP19 application is inactive.
