### ISSUE TITLE
Systems4you

### ISSUE THREAD

**Issue by jamiew** [dewi-alliance/hotspot-manufacturers#43]
Name: Systems4you
 Author: @diogo24m
 Created: 2021-07-28
 Original PR: https://github.com/helium/HIP/pull/248
 Status: reviewing
 
 Rendered view: https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/systems4you.md

**Comment by ChristinaR04** [comment]
Closed, this HIP19 application is inactive.
