### ISSUE TITLE
Weimaisi Technology

### ISSUE THREAD

**Issue by Sophi** [dewi-alliance/hotspot-manufacturers#49]
Name: Weimaisi Technology
Author: @summerflyslk20
Created: 2021-08-09
Original PR: helium/HIP#258 
Status: reviewing

Rendered view: https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/weimaisi.md

**Comment by Sophi** [comment]
@summerflyslk20 hello and welcome! please complete the hardware information on your proposal and provide a way to contact you.

**Comment by ChristinaR04** [comment]
Closed, this HIP19 application is inactive.
