### ISSUE TITLE
Chipmatrix

### ISSUE THREAD

**Issue by Sophi** [dewi-alliance/hotspot-manufacturers#65]
Name: Chipmatrix
Author: @chipmatrixcn 
Created: 2021-08-23
Original PR: dewi/HIP#58
Status: reviewing

Application link: https://github.com/chipmatrixcn/hotspot-manufacturers/blob/9457659feb2641fdc3f228e54b75e6c4d298c7a0/chipmatrix.md

**Comment by ChristinaR04** [comment]
Closed, this HIP19 application is inactive.
