### ISSUE TITLE
iBudget PCS

### ISSUE THREAD

**Issue by Sophi** [dewi-alliance/hotspot-manufacturers#81]
Name: iBudget PCS
Author: @mmaalouf97 
Created: 7/16/21
Original: helium/HIP/pull/235
Status: reviewing
Rendered view: https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/ibudgetpcs.md

**Comment by ChristinaR04** [comment]
Closed, this HIP19 application is inactive.
